"""remove test_field

Revision ID: dd6cda446572
Revises: c982713e15ea
Create Date: 2026-03-09 20:07:38.493237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd6cda446572'
down_revision: Union[str, Sequence[str], None] = 'c982713e15ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shorter_urls', 'test_field')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shorter_urls', sa.Column('test_field', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
